services:
  - type: web
    name: character-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd Backend && uvicorn main:app --host 0.0.0.0 --port $PORT --proxy-headers
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
  
  - type: web
    name: character-ai-frontend
    env: python
    buildCommand: pip install -r frontend/requirements.txt
    startCommand: streamlit run frontend/app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
