services:
  - type: web
    name: character-ai-backend
    env: docker
    dockerContext: ./Backend
    dockerfilePath: ./Backend/Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0

  - type: web
    name: character-ai-frontend
    env: docker
    dockerContext: ./frontend
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
